node('maven')  
        {
         stage 'BuildDev'
         openshiftBuild(namespace: 'pf-dev', buildConfig: 'pf', showBuildLogs: 'true')
         stage 'VerifyBuild'
         openshiftVerifyBuild(namespace: 'pf-dev', buildConfig: 'pf') 
         stage 'DeployTest'
         openshiftDeploy(namespace: 'pf-qa', deploymentConfig: 'pf', showBuildLogs: 'true')
         stage 'VerifyDeploymentTest'
         openshiftVerifyDeployment(namespace: 'pf-qa', deploymentConfig: 'pf')
         stage('Promote to Prod?') {
                  timeout(time:15, unit:'MINUTES') {
                      input message: "Promote to Prod?", ok: "Promote"
                }
                openshiftDeploy(namespace: 'pf-prod', deploymentConfig: 'pf', showBuildLogs: 'true')
          }
         } 
