kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipelinefromgit"
spec:
  source:
    git:
      uri: "https://github.com/openpabz/pf-pipeline"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/pfpipeline.jenkins 
